// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/schedules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista horarios con filtros opcionales y paginación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Listar horarios",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Tamaño de página",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por grupo académico",
                        "name": "academic_group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por instructor",
                        "name": "instructor_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por ambiente",
                        "name": "venue_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por día de la semana (1-7)",
                        "name": "day_of_week",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ACTIVE",
                            "CANCELLED",
                            "SUSPENDED"
                        ],
                        "type": "string",
                        "description": "Filtrar por estado",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.PaginatedResponse-scheduleservice_internal_application_dtos_ScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo horario en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Crear horario",
                "parameters": [
                    {
                        "description": "Datos del horario",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.CreateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.ScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/schedules/bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea múltiples horarios en una sola operación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules",
                    "bulk"
                ],
                "summary": "Crear horarios masivamente",
                "parameters": [
                    {
                        "description": "Lista de horarios a crear",
                        "name": "schedules",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.BulkCreateSchedulesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.BulkCreateSchedulesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/schedules/upload-csv": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Procesa un archivo CSV para crear múltiples horarios",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules",
                    "bulk"
                ],
                "summary": "Cargar horarios desde CSV",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Archivo CSV con horarios",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.CSVUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/schedules/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene un horario específico por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Obtener horario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del horario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.ScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza un horario existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Actualizar horario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del horario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.UpdateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduleservice_internal_application_dtos.ScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina un horario del sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Eliminar horario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del horario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "scheduleservice_internal_application_dtos.AcademicGroupResponse": {
            "type": "object",
            "properties": {
                "academic_program": {
                    "$ref": "#/definitions/scheduleservice_internal_application_dtos.AcademicProgramResponse"
                },
                "academic_program_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "number": {
                    "type": "string",
                    "example": "2691698"
                },
                "quarter": {
                    "type": "integer",
                    "example": 3
                },
                "shift": {
                    "type": "string",
                    "example": "MANANA"
                },
                "updated_at": {
                    "type": "string"
                },
                "year": {
                    "type": "integer",
                    "example": 2024
                }
            }
        },
        "scheduleservice_internal_application_dtos.AcademicProgramResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ADSO"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "Programa de formación en desarrollo de software"
                },
                "duration": {
                    "type": "integer",
                    "example": 24
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Análisis y Desarrollo de Software"
                },
                "type": {
                    "type": "string",
                    "example": "TECNOLOGO"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "scheduleservice_internal_application_dtos.BulkCreateSchedulesRequest": {
            "type": "object",
            "required": [
                "schedules"
            ],
            "properties": {
                "schedules": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/scheduleservice_internal_application_dtos.CreateScheduleRequest"
                    }
                }
            }
        },
        "scheduleservice_internal_application_dtos.BulkCreateSchedulesResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduleservice_internal_application_dtos.ScheduleResponse"
                    }
                },
                "errors": {
                    "type": "integer"
                },
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduleservice_internal_application_dtos.BulkError"
                    }
                },
                "succeeded": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "scheduleservice_internal_application_dtos.BulkError": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                }
            }
        },
        "scheduleservice_internal_application_dtos.CSVError": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "row": {
                    "type": "integer"
                }
            }
        },
        "scheduleservice_internal_application_dtos.CSVUploadResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduleservice_internal_application_dtos.ScheduleResponse"
                    }
                },
                "error_rows": {
                    "type": "integer"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduleservice_internal_application_dtos.CSVError"
                    }
                },
                "processed_rows": {
                    "type": "integer"
                },
                "success_rows": {
                    "type": "integer"
                },
                "summary": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "scheduleservice_internal_application_dtos.CampusResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Calle 44 No. 1-104"
                },
                "city": {
                    "type": "string",
                    "example": "Mocoa"
                },
                "code": {
                    "type": "string",
                    "example": "CGDSS"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Centro de Gestión y Desarrollo Sostenible Suroccidente"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "scheduleservice_internal_application_dtos.CreateScheduleRequest": {
            "type": "object",
            "required": [
                "academic_group_id",
                "block_identifier",
                "day_of_week",
                "end_date",
                "end_time",
                "instructor_id",
                "start_date",
                "start_time",
                "subject",
                "venue_id"
            ],
            "properties": {
                "academic_group_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "block_identifier": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 4,
                    "example": "MLUN1"
                },
                "day_of_week": {
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 1,
                    "example": 1
                },
                "end_date": {
                    "type": "string",
                    "example": "2024-06-15"
                },
                "end_time": {
                    "type": "string",
                    "example": "10:00"
                },
                "instructor_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "start_date": {
                    "type": "string",
                    "example": "2024-01-15"
                },
                "start_time": {
                    "type": "string",
                    "example": "08:00"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 3,
                    "example": "Programación de Software"
                },
                "venue_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                }
            }
        },
        "scheduleservice_internal_application_dtos.PaginatedResponse-scheduleservice_internal_application_dtos_ScheduleResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduleservice_internal_application_dtos.ScheduleResponse"
                    }
                },
                "links": {
                    "$ref": "#/definitions/scheduleservice_internal_application_dtos.PaginationLinks"
                },
                "pagination": {
                    "$ref": "#/definitions/scheduleservice_internal_application_dtos.PaginationMeta"
                }
            }
        },
        "scheduleservice_internal_application_dtos.PaginationLinks": {
            "type": "object",
            "properties": {
                "first": {
                    "type": "string"
                },
                "last": {
                    "type": "string"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                },
                "self": {
                    "type": "string"
                }
            }
        },
        "scheduleservice_internal_application_dtos.PaginationMeta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "scheduleservice_internal_application_dtos.ScheduleResponse": {
            "type": "object",
            "properties": {
                "academic_group": {
                    "$ref": "#/definitions/scheduleservice_internal_application_dtos.AcademicGroupResponse"
                },
                "academic_group_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "block_identifier": {
                    "type": "string",
                    "example": "MLUN1"
                },
                "created_at": {
                    "type": "string"
                },
                "day_of_week": {
                    "type": "integer",
                    "example": 1
                },
                "day_of_week_name": {
                    "type": "string",
                    "example": "Lunes"
                },
                "end_date": {
                    "type": "string",
                    "example": "2024-06-15"
                },
                "end_time": {
                    "type": "string",
                    "example": "10:00"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "instructor_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "start_date": {
                    "type": "string",
                    "example": "2024-01-15"
                },
                "start_time": {
                    "type": "string",
                    "example": "08:00"
                },
                "status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "subject": {
                    "type": "string",
                    "example": "Programación de Software"
                },
                "updated_at": {
                    "type": "string"
                },
                "venue": {
                    "$ref": "#/definitions/scheduleservice_internal_application_dtos.VenueResponse"
                },
                "venue_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                }
            }
        },
        "scheduleservice_internal_application_dtos.UpdateScheduleRequest": {
            "type": "object",
            "properties": {
                "academic_group_id": {
                    "type": "string"
                },
                "block_identifier": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 4
                },
                "day_of_week": {
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 1
                },
                "end_date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "instructor_id": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "CANCELLED",
                        "SUSPENDED"
                    ]
                },
                "subject": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 3
                },
                "venue_id": {
                    "type": "string"
                }
            }
        },
        "scheduleservice_internal_application_dtos.VenueResponse": {
            "type": "object",
            "properties": {
                "campus": {
                    "$ref": "#/definitions/scheduleservice_internal_application_dtos.CampusResponse"
                },
                "campus_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "capacity": {
                    "type": "integer",
                    "example": 30
                },
                "code": {
                    "type": "string",
                    "example": "LAB-SW-01"
                },
                "created_at": {
                    "type": "string"
                },
                "floor": {
                    "type": "string",
                    "example": "2"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Laboratorio de Software"
                },
                "type": {
                    "type": "string",
                    "example": "LABORATORIO"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8002",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Schedule Service API",
	Description:      "API para gestión de horarios académicos con operaciones bulk",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
