// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Equipo de Desarrollo SICORA",
            "email": "dev@sicora.sena.edu.co"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appeals": {
            "post": {
                "description": "Create a new appeal for a student case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appeals"
                ],
                "summary": "Create a new appeal",
                "parameters": [
                    {
                        "description": "Appeal information",
                        "name": "appeal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CreateAppealRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.AppealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/appeals/student/{student_id}": {
            "get": {
                "description": "Get all appeals for a specific student",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appeals"
                ],
                "summary": "Get appeals by student ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.AppealResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/appeals/{id}": {
            "get": {
                "description": "Get an appeal by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appeals"
                ],
                "summary": "Get appeal by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appeal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.AppealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/appeals/{id}/process": {
            "patch": {
                "description": "Process an appeal with decision",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appeals"
                ],
                "summary": "Process appeal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appeal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Appeal decision",
                        "name": "decision",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/committees": {
            "get": {
                "description": "Get all committees",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "committees"
                ],
                "summary": "Get all committees",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new committee with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "committees"
                ],
                "summary": "Create a new committee",
                "parameters": [
                    {
                        "description": "Committee information",
                        "name": "committee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CreateCommitteeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/committees/by-center": {
            "get": {
                "description": "Get committees by center",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "committees"
                ],
                "summary": "Get committees by center",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Center name",
                        "name": "center",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/committees/by-type": {
            "get": {
                "description": "Get committees by type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "committees"
                ],
                "summary": "Get committees by type",
                "parameters": [
                    {
                        "enum": [
                            "DISCIPLINARY",
                            "ACADEMIC"
                        ],
                        "type": "string",
                        "description": "Committee type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/committees/{id}": {
            "get": {
                "description": "Get a committee by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "committees"
                ],
                "summary": "Get committee by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Committee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a committee by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "committees"
                ],
                "summary": "Update committee",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Committee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Committee update information",
                        "name": "committee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.UpdateCommitteeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a committee by its ID",
                "tags": [
                    "committees"
                ],
                "summary": "Delete committee",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Committee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/improvement-plans": {
            "post": {
                "description": "Create a new improvement plan for a student case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "improvement-plans"
                ],
                "summary": "Create a new improvement plan",
                "parameters": [
                    {
                        "description": "Improvement plan information",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CreateImprovementPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ImprovementPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/improvement-plans/student-case/{student_case_id}": {
            "get": {
                "description": "Get all improvement plans for a specific student case",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "improvement-plans"
                ],
                "summary": "Get improvement plans by student case ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student Case ID",
                        "name": "student_case_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.ImprovementPlanResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/improvement-plans/{id}": {
            "get": {
                "description": "Get an improvement plan by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "improvement-plans"
                ],
                "summary": "Get improvement plan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Improvement Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ImprovementPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an improvement plan by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "improvement-plans"
                ],
                "summary": "Update improvement plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Improvement Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Improvement plan updates",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.UpdateImprovementPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ImprovementPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/improvement-plans/{id}/progress": {
            "patch": {
                "description": "Update progress and notes of an improvement plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "improvement-plans"
                ],
                "summary": "Update improvement plan progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Improvement Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Progress information",
                        "name": "progress",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sanctions": {
            "post": {
                "description": "Create a new sanction for a student case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sanctions"
                ],
                "summary": "Create a new sanction",
                "parameters": [
                    {
                        "description": "Sanction information",
                        "name": "sanction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CreateSanctionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.SanctionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sanctions/student/{student_id}": {
            "get": {
                "description": "Get all sanctions for a specific student",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sanctions"
                ],
                "summary": "Get sanctions by student ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.SanctionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sanctions/{id}": {
            "get": {
                "description": "Get a sanction by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sanctions"
                ],
                "summary": "Get sanction by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sanction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.SanctionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sanctions/{id}/activate": {
            "patch": {
                "description": "Activate a specific sanction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sanctions"
                ],
                "summary": "Activate sanction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sanction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sanctions/{id}/complete": {
            "patch": {
                "description": "Mark a sanction as completed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sanctions"
                ],
                "summary": "Complete sanction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sanction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student-cases": {
            "post": {
                "description": "Create a new student case with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-cases"
                ],
                "summary": "Create a new student case",
                "parameters": [
                    {
                        "description": "Student case information",
                        "name": "case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.CreateStudentCaseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.StudentCaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student-cases/by-student": {
            "get": {
                "description": "Get student cases by student ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-cases"
                ],
                "summary": "Get student cases by student ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.StudentCaseResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student-cases/overdue": {
            "get": {
                "description": "Get all overdue student cases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-cases"
                ],
                "summary": "Get overdue student cases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.StudentCaseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student-cases/pending": {
            "get": {
                "description": "Get all pending student cases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-cases"
                ],
                "summary": "Get pending student cases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mevalservice_internal_application_dto.StudentCaseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student-cases/{id}": {
            "get": {
                "description": "Get a student case by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-cases"
                ],
                "summary": "Get student case by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student case ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.StudentCaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a student case by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-cases"
                ],
                "summary": "Update student case",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student case ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student case update information",
                        "name": "case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.UpdateStudentCaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.StudentCaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mevalservice_internal_application_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mevalservice_internal_application_dto.AppealResponse": {
            "type": "object",
            "properties": {
                "appeal_number": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "evidence": {
                    "type": "string"
                },
                "final_resolution": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "justification": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "requested_resolution": {
                    "type": "string"
                },
                "resolution_date": {
                    "type": "string"
                },
                "review_date": {
                    "type": "string"
                },
                "reviewer_notes": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "student_case_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "submission_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.CommitteeDecisionResponse": {
            "type": "object",
            "properties": {
                "attendees_list": {
                    "type": "string"
                },
                "committee_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "decision_date": {
                    "type": "string"
                },
                "decision_number": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "execution_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "justification": {
                    "type": "string"
                },
                "president_signature": {
                    "type": "boolean"
                },
                "resolution": {
                    "type": "string"
                },
                "secretary_signature": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "student_case_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "voting_result": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.CommitteeMemberResponse": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "committee_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.CommitteeResponse": {
            "type": "object",
            "properties": {
                "center": {
                    "type": "string"
                },
                "coordinator": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_members": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "max_members": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeMemberResponse"
                    }
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.CreateAppealRequest": {
            "type": "object",
            "required": [
                "description",
                "justification",
                "requested_resolution",
                "student_case_id",
                "student_id",
                "subject",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "minLength": 10
                },
                "evidence": {
                    "type": "string"
                },
                "justification": {
                    "type": "string",
                    "minLength": 10
                },
                "priority": {
                    "type": "string",
                    "enum": [
                        "LOW",
                        "MEDIUM",
                        "HIGH",
                        "URGENT"
                    ]
                },
                "requested_resolution": {
                    "type": "string",
                    "minLength": 10
                },
                "student_case_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "SANCTION_APPEAL",
                        "DECISION_APPEAL",
                        "PROCESS_APPEAL"
                    ]
                }
            }
        },
        "mevalservice_internal_application_dto.CreateCommitteeRequest": {
            "type": "object",
            "required": [
                "center",
                "coordinator",
                "max_members",
                "name",
                "type"
            ],
            "properties": {
                "center": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "coordinator": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "max_members": {
                    "type": "integer",
                    "maximum": 15,
                    "minimum": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "DISCIPLINARY",
                        "ACADEMIC"
                    ]
                }
            }
        },
        "mevalservice_internal_application_dto.CreateImprovementPlanRequest": {
            "type": "object",
            "required": [
                "activities",
                "description",
                "end_date",
                "objectives",
                "start_date",
                "student_case_id",
                "student_id",
                "supervisor_id",
                "timeline",
                "title"
            ],
            "properties": {
                "activities": {
                    "type": "string",
                    "minLength": 10
                },
                "description": {
                    "type": "string",
                    "minLength": 10
                },
                "end_date": {
                    "type": "string"
                },
                "objectives": {
                    "type": "string",
                    "minLength": 10
                },
                "resources": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "student_case_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "supervisor_id": {
                    "type": "string"
                },
                "timeline": {
                    "type": "string",
                    "minLength": 10
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5
                }
            }
        },
        "mevalservice_internal_application_dto.CreateSanctionRequest": {
            "type": "object",
            "required": [
                "description",
                "justification",
                "severity",
                "start_date",
                "student_case_id",
                "student_id",
                "title",
                "type"
            ],
            "properties": {
                "appeal_deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "minLength": 10
                },
                "end_date": {
                    "type": "string"
                },
                "is_appealable": {
                    "type": "boolean"
                },
                "justification": {
                    "type": "string",
                    "minLength": 10
                },
                "severity": {
                    "type": "string",
                    "enum": [
                        "MINOR",
                        "MODERATE",
                        "SEVERE",
                        "CRITICAL"
                    ]
                },
                "start_date": {
                    "type": "string"
                },
                "student_case_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "WARNING",
                        "CONDITIONAL_ENROLLMENT",
                        "ENROLLMENT_CANCELLATION"
                    ]
                }
            }
        },
        "mevalservice_internal_application_dto.CreateStudentCaseRequest": {
            "type": "object",
            "required": [
                "committee_id",
                "description",
                "reported_by",
                "severity",
                "student_id",
                "title",
                "type"
            ],
            "properties": {
                "committee_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "minLength": 10
                },
                "due_date": {
                    "type": "string"
                },
                "evidence": {
                    "type": "string"
                },
                "priority": {
                    "type": "string",
                    "enum": [
                        "LOW",
                        "MEDIUM",
                        "HIGH",
                        "URGENT"
                    ]
                },
                "reported_by": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "severity": {
                    "type": "string",
                    "enum": [
                        "MINOR",
                        "MODERATE",
                        "SEVERE",
                        "CRITICAL"
                    ]
                },
                "student_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "DISCIPLINARY",
                        "ACADEMIC"
                    ]
                }
            }
        },
        "mevalservice_internal_application_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.ImprovementPlanResponse": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "string"
                },
                "completion_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "objectives": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "resources": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "student_case_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "supervisor_id": {
                    "type": "string"
                },
                "supervisor_notes": {
                    "type": "string"
                },
                "timeline": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.SanctionResponse": {
            "type": "object",
            "properties": {
                "appeal_deadline": {
                    "type": "string"
                },
                "completion_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_appealable": {
                    "type": "boolean"
                },
                "justification": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "student_case_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.StudentCaseResponse": {
            "type": "object",
            "properties": {
                "appeals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mevalservice_internal_application_dto.AppealResponse"
                    }
                },
                "case_number": {
                    "type": "string"
                },
                "committee": {
                    "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeResponse"
                },
                "committee_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "decisions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mevalservice_internal_application_dto.CommitteeDecisionResponse"
                    }
                },
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "evidence": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "improvement_plans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mevalservice_internal_application_dto.ImprovementPlanResponse"
                    }
                },
                "priority": {
                    "type": "string"
                },
                "report_date": {
                    "type": "string"
                },
                "reported_by": {
                    "type": "string"
                },
                "resolution_date": {
                    "type": "string"
                },
                "sanctions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mevalservice_internal_application_dto.SanctionResponse"
                    }
                },
                "severity": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.UpdateCommitteeRequest": {
            "type": "object",
            "properties": {
                "coordinator": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "max_members": {
                    "type": "integer",
                    "maximum": 15,
                    "minimum": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "INACTIVE"
                    ]
                }
            }
        },
        "mevalservice_internal_application_dto.UpdateImprovementPlanRequest": {
            "type": "object",
            "properties": {
                "completion_date": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "IN_PROGRESS",
                        "COMPLETED",
                        "FAILED"
                    ]
                },
                "supervisor_notes": {
                    "type": "string"
                }
            }
        },
        "mevalservice_internal_application_dto.UpdateStudentCaseRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "minLength": 10
                },
                "due_date": {
                    "type": "string"
                },
                "evidence": {
                    "type": "string"
                },
                "priority": {
                    "type": "string",
                    "enum": [
                        "LOW",
                        "MEDIUM",
                        "HIGH",
                        "URGENT"
                    ]
                },
                "resolution_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "IN_PROGRESS",
                        "RESOLVED",
                        "APPEALED",
                        "CLOSED"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SICORA mevalservice API",
	Description:      "Microservicio mevalservice del Sistema de Información de Coordinación Académica (SICORA) - SENA",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
